name: sac
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.10.2
  - cudatoolkit=11.1.1
  - pip=22.0.3
  - pip:
    - gym==0.21.0
    - mujoco-py==2.1.2.14
    - ray[rllib]==1.10.0