name: sac2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.10.2
  - cudatoolkit=11.1.1
  - seaborn=0.11.2
  - scipy=1.8.0
  - numpy=1.22.2
  - parameterized=0.8.1
  - pip=22.0.3
  - pip:
    - gym==0.21.0
    - mujoco-py==2.1.2.14